### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [paulwedeck/settlers-remake#43]
Original devs agreed for it to be included https://github.com/jsettlers/settlers-remake/issues/627

Your fork builds fine: https://gitlab.com/fdroid/rfp/-/issues/264#note_916709259 but, we'd want your answer if this is ok with you.

Second, maybe bring versioning in line, eg. [tagged v0.6-alpha](https://github.com/paulwedeck/settlers-remake/releases/tag/v0.6-alpha) vs [android 0.0.1](https://github.com/paulwedeck/settlers-remake/blob/master/jsettlers.main.android/build.gradle#L11-L12)

Third, we'd like you to include some metadata here in the repo, screenshots/description/changelog/etc: https://gitlab.com/-/snippets/1895688 _(this helps as you can update them here and F-Droid will pick them out)_

**Comment by paulwedeck** [comment]
> we'd want your answer if this is ok with you

Yes, this is fine with me and I will look into the issues you pointed out.

**Comment by licaon-kter** [comment]
https://github.com/paulwedeck/settlers-remake/commit/4aec7748b3e0855da6d1008dc7870699147d9f8d#diff-3fe924c935640ab34cd6a5feb37fd63022915fc54eb3dc60c5bb67e3c44112cfR28 lol wut? 

We can't use an ever changing versionCode :) :)

That's an odd choice...

**Comment by paulwedeck** [comment]
What is wrong with that?
We could use the date of the latest commit if the versionCode has to be reproducible but IMO this is the best choice because it means that all newer builds will supersede older builds.

**Comment by licaon-kter** [comment]
The build time is not fixed, eg. I'll merge a new version today and that would be build sometimes...in the next hour/day/week. 

So yeah, make it fixed, eg. 1, 1000, 123455 or if you want to have it tied to something use the commit date.

Now, it depends on app/you, we can even set the recipe so that the F-Droid checkupdate bot picks up new releases when you/dev tags. Else one needs to come to F-Droid Data and open a Merge Request to add a new version.

How is the release cycle for this app? You decide from time to time to Tag a new one?

**Comment by paulwedeck** [comment]
>The build time is not fixed

Yes but does this really matter?
[Google says](https://developer.android.com/studio/publish/versioning) that the versionCode is only used to distinguish newer from older versions. Later builds will in most circumstances be more recent than older ones.

> You decide from time to time to Tag a new one?

Yes, there is no constant development schedule.
This means that sometimes there are enough new features every couple of weeks or there is no development for a month or so.

**Comment by licaon-kter** [comment]
_"the build time OF THE F-DROID SURVER is not fixed"_

**Comment by paulwedeck** [comment]
Sure but it should always build the newer version after previous version.
This means that the newer version will always get the higher/more recent versionCode

**Comment by licaon-kter** [comment]
I've detailed more above.

**Comment by licaon-kter** [comment]
Given the current setup of this repo, I can set the recipe to put static versionCode/Name straight into build.gradle at built time. They'll be the ones decided when the recipe is merged in F-Droid Data.

It won't matter to the users, or you actually, since given that we build from a certain git commit, that's the best reference anyway.

**Comment by licaon-kter** [comment]
Here's a build block for reference:
```
  - versionName: v0.6-alpha-31-g4aec7748b
    versionCode: 22041908
    commit: 4aec7748b3e0855da6d1008dc7870699147d9f8d
    subdir: jsettlers.main.android
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y openjdk-11-jdk-headless
      - update-alternatives --auto java
    gradle:
      - yes
    prebuild:
      - sed -i -e '/laenger/d' -e '/mavenCentral()/ajcenter()' ../build.gradle
      - sed -i -e 's/vpbs:0.0.5/vpbs:0.0.6/' build.gradle
    scandelete:
      - jsettlers.tests/libs/
```

The build server pulls the metadata when a cycle starts ( https://monitor.f-droid.org/builds/running ) and builds the new apps and yours. It might take a few hours or a day, depends on apps build times and their number. Hence any versionCode/Name that is time dependant will never be correct and it's (for F-Droid) unusable (in this form).

I can just `sed` 2 strings in https://github.com/paulwedeck/settlers-remake/blob/master/jsettlers.main.android/build.gradle#L39-L40 to set them as the build recipe says and be done. :)
