### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by JakobDev** [paulwedeck/settlers-remake#58]
Would you be interested to build a Flatpak publish it on [Flathub](https://flathub.org/)? Would not be much work. Just package JSettlers together with OpenJDK. This would allow a easy one click install and automatic Updates on most Linux distros. I can create a Manifest and do the Maintaining, if you want.

**Comment by paulwedeck** [comment]
I am open to the idea but I don't have any experience with flatpacks or flathub so I would appreciate it if you could create the manifest file.
For this I have created a repo according to the guide on the flathub wiki.
https://github.com/paulwedeck/flathub-jsettlers

JSettlers is build with the gradle tasks releaseJSettlers, releaseDedicatedServer and releaseAndroid. If you intend to include all three into the flatpack than "release" is enough. I don't really see a point in including the apk though because installing the apk is far more difficult than downloading it. Also JSettlers will probably be included in ODroid if I come around creating the files and so on.
All building artifacts are in release/
JSettlers needs read only access to a previous S3 installation and read write access to ~/.jsettlers/ and its working directory.

I hope this helps

**Comment by JakobDev** [comment]
I have now created a Manifest. Place this 2 files in the same directory:

com.github.paulwedeck.settlers-remake.yaml
```yaml
app-id: com.github.paulwedeck.settlers-remake
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
command: jsettlers
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk11
finish-args:
  - --socket=x11
  - --share=ipc
  - --device=dri
  - --share=network
  - --socket=pulseaudio
  - --filesystem=host

modules: 
  - name: openjdk
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/openjdk11/install.sh

  - name: jsettlers
    buildsystem: simple
    build-commands:
      - mkdir -p $FLATPAK_DEST/JSettlers
      - cp -r * $FLATPAK_DEST/JSettlers
      - install -Dm755 jsettlers.sh $FLATPAK_DEST/bin/jsettlers
    sources:
      - type: archive
        url: https://github.com/paulwedeck/settlers-remake/releases/download/v0.6-alpha/JSettlers.zip
        sha256: 95f9cff16f0cd0a874910a6abf31440ee568f37a336a12511087368d97eb9116
      - type: file
        path: jsettlers.sh
```

jsettlers.sh:
```sh
#!/bin/sh
/app/jre/bin/java -jar /app/JSettlers/JSettlers.jar
```

And run this commands:
```sh
# Install decencies
flatpak install org.flatpak.Builder org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08 org.freedesktop.Sdk.Extension.openjdk11//21.08
# Build and install
flatpak run org.flatpak.Builder build-dir com.github.paulwedeck.settlers-remake.yaml --force-clean --install --user
# Run
flatpak run com.github.paulwedeck.settlers-remake 
```

I was able to start a test game. It looks like everything is working. The Flatpak only misses some data files such as a icon and a .desktop file. You can open a interactive shell inside the Flatpak with` flatpak run --command=bash com.github.paulwedeck.settlers-remake `.

 have not build it from source. This would be a huge pain in a Flatpak without network access and I know nobody who does this for Java. Is this only Java code or has a Lib some native binary? I'm asking because Flathub supports ARM too.

A problem is currently how to choose the directory of Settlers 3. Normally Flatpak Apps request a Filedialog with a D-Bus Interface and the Flatpak get only access to the File the User chooses. This is done automatically if you use Gtk or Qt, but not in Java. So this Flatpak has currently acess to all Files. As a Workaround you can use the `zenity --file-selection --directory --title "Settlers"` terminal command.This opens a Filedialog and prints the chosen path.

> and read write access to ~/.jsettlers/

Please use the  [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). If the `$XDG_DATA_HOME ` environment variable is set set, use `$XDG_DATA_HOME /jsettlers`, if not use `~/.local/share/jsettlers`.

> For this I have created a repo according to the guide on the flathub wiki.
> https://github.com/paulwedeck/flathub-jsettlers

This is only needed for the submission, when everything is ready.

**Comment by paulwedeck** [comment]
JSettlers mostly just needs LWJGL native libraries. I never tested it on arm but it should work fine.

> As a Workaround you can use the zenity --file-selection --directory --title "Settlers" terminal command.

This isn't a cross platform solution so this would be a feature specifically for the flatpak.
Is there an environment variable that indicates that the jar runs inside a flatpak?
Is FLATPAK_ID a good indicator for this?

I will look into moving the config directory

**Comment by JakobDev** [comment]
> This isn't a cross platform solution so this would be a feature specifically for the flatpak.

zenity is not Flatpak specific. It's a little tool fur shell scripts to have a GUI Dialogs. Since it uses GTK, you can use it for the Filedialog. It is included in the Flatpak runtime, but is also installed on many Systems outside Flatpak. Since the Filedialog is better than the Java one, you should just check if zenity in in the PATH, if yes, use it, if not use the current Dialog.

If you have some experience with D-Bus, you [can call the Portal directly](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser). If not, you should just use zenity. In my experience the D-Bus libs for most programming languages are not in a good state, have a bad documentation and lack examples. So you should better use your time to bring JSettlers out of Alpha and use zenity to open a Gtk Filedialog.

You can remove `--filesystem=host` from the finish-args in the manifest to disable access to the host filesystem, to test if it works.
> 
> Is there an environment variable that indicates that the jar runs inside a flatpak?
> Is FLATPAK_ID a good indicator for this?

YOu can look if the file /.flatpak-info exists.

**Comment by paulwedeck** [comment]
I think the current file dialog is better because it gives direct feedback if the selected directory is correct or not. Otherwise users might select the GFX directory or the S3.EXE or the parent directory of the installation and not the directory itself.

I pushed some commits which both change the config directory to $XDG_CONFIG_HOME/jsettlers and use zenity if the application is run as a flatpak

**Comment by JakobDev** [comment]
It works now with disabled access to the host filesystem. It also saves the files now in the correct folder. But think you should show a message box that explains what directory the User should choose in the upcoming dialog instead of opening a file dialog. directly on startup, which is a confusing for the User. You may also should use a better window title of the file dialog (can be set with the --title argument) like "Choose game directory" or something else.

I guess [this is the Icon](https://github.com/paulwedeck/settlers-remake/blob/master/jsettlers.mapcreator/src/main/resources/jsettlers/mapcreator/main/window/icon.png) that I should use for the App.

Flathub requires at least one Screenshot. Can you provide a stable link to one?

I also need a description that is shown on the Flathub website and in the sofware centers.

**Comment by paulwedeck** [comment]
I uploaded some screenshots. This should be a stable link: https://github.com/paulwedeck/settlers-remake/tree/0b4a2424f4b511777c70b0ed3971261cf2af9e53/docs/screenshots

I also added an additional window before the select dialog that clarifies what we want.

Description:
```JSettlers is an open source remake of the game The Settlers III by BlueByte. The main goal of the game is to build an economy and fight other players. JSettlers needs the graphics files from an original Settlers III installation. The demo version work as well but only contains Roman and Amazon graphics files.```

What do you think about this?

**Comment by JakobDev** [comment]
i created #59 to add needed data files. These are now the files needed for building the Flatpak after merging:

com.github.paulwedeck.settlers-remake.yaml
```yaml
app-id: com.github.paulwedeck.settlers-remake
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
command: jsettlers
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk11
finish-args:
  - --socket=x11
  - --share=ipc
  - --device=dri
  - --share=network
  - --socket=pulseaudio

modules: 
  - name: openjdk
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/openjdk11/install.sh

  - name: jsettlers
    buildsystem: simple
    build-commands:
      - mkdir -p $FLATPAK_DEST/JSettlers
      - cp -r * $FLATPAK_DEST/JSettlers
      - install -Dm755 jsettlers.sh $FLATPAK_DEST/bin/jsettlers
      - install -Dm755 jsettlers-mapcreator.sh $FLATPAK_DEST/bin/jsettlers-mapcreator
      - install -Dm644 icon.png  $FLATPAK_DEST/share/icons/hicolor/scalable/apps/$FLATPAK_ID.png
      - install -Dm644 dist/linux/com.github.paulwedeck.settlers-remake.desktop -t  $FLATPAK_DEST/share/applications
      - install -Dm644 dist/linux/com.github.paulwedeck.settlers-remake.mapcreator.desktop -t  $FLATPAK_DEST/share/applications
      - install -Dm644 dist/linux/com.github.paulwedeck.settlers-remake.metainfo.xml -t  $FLATPAK_DEST/share/metainfo
    sources:
      #- type: archive
       # url: https://github.com/paulwedeck/settlers-remake/releases/download/v0.6.0.2-alpha/JSettlers.zip
        #sha256: 9275c2155f84deae955269b629a024bc443c1cc70e7aefd04f31126f5fcb4353
      - type: archive
        path: JSettlers.zip
      - type: file
        path: jsettlers.sh
      - type: file
        path: jsettlers-mapcreator.sh
```

jsettlers.sh
```sh
#!/bin/sh
/app/jre/bin/java -jar /app/JSettlers/JSettlers.jar
```

jsettlers-mapcreator.sh
```sh
#!/bin/sh
/app/jre/bin/java -jar /app/JSettlers/MapCreator.jar
```

The manifest uses currently the JSettlers.zip from the same directory as the manifest for testing purposes. If you are ready, release a new version and edit the sources, so it will download the JSettlers.zip from GitHub.

Please carefully test this before publishing. To build it, use the commands above.

Things you should may do: The .desktop file of JSettlers has a Icon while the Window uses the standard Java Icon. You should give the Window the Icon. You should also add localisation for the new added texts.

If you are ready to publish, fork the new-pr (not the master) branch of https://github.com/flathub/flathub and add your files. Than make a PR against the new-pr branch. Your manifest will be reviewed and if everything is correct, your manifest will be merged into a new repo under the flathub organisation and JSettlers will be aviable on Flathub.
